### ISSUE TITLE
Unable to accept SSID with spaces

### ISSUE THREAD

**Issue by zerrandrew21** [jpkrause/AndroidProxySetter#5] opened 2015-06-22 17:56 UTC
I was using your tool today to setup a proxy for a Fire TV. Everything seems to work up until the point of registering the SSID. It seems that if there are spaces in the SSID the program does not correctly register the SSID. We've used single quotes as well as double quotes with nothing working as long as there is a space involved.

**Comment by manadream** [comment] 2015-06-23 17:40
Thanks for reporting this. I'll take a look and get a fix in for you as soon as possible.

**Comment by manadream** [comment] 2015-06-23 20:14
@zerrandrew21 So the problem I encountered with using an SSID that has a space in it is that the intent passing mechanism of adb will not pass in a space unless it is properly formatted.
To correctly pass an SSID with a space using the command line on bash (OSX or Linux) you need to espace the space AND surround it with quotations like so:
`adb shell am start -n tk.elevenk.proxysetter/.MainActivity -e host 192.168.56.1 -e port 8080 -e ssid "Public\ Wifi" -e reset-wifi true`

What is the command and shell that you are using to execute this? Can you post your adb logs from when you execute this command?

**Comment by zerrandrew21** [comment] 2015-06-23 20:25
I'd love to post logs if I could but unfortunately dealing with proprietary
information. Logs would probably get me fired, heh. I can tell you though
that we used the correct commands. We just didn't escape the spaces. We
ended up renaming the network to utilize it so I'll have to set up a test
network at home to test it out. If I run into any problems there I'll be
sure to get you everything needed.

**Comment by manadream** [comment] 2015-06-23 20:32
Of course, I understand. To filter out all messages except for the ones made by this tool you can run `adb logcat -s ProxySetterApp`
I have a feeling it may have been problematic because of the lack of escaped spaces, but I may be wrong. I'll leave this open until we determine the problem.

**Comment by manadream** [comment] 2015-07-17 01:47
@zerrandrew21 is this still a problem for you?

**Comment by manadream** [comment] 2015-08-30 07:00
Closing as expected behavior since spaces need to be escaped on the command line

**Closed as completed by manadream** 2015-08-30 07:00 UTC
